### PR TITLE
Stratigraphy metrics

### PR DESCRIPTION
**Pull request by amoodie**
# Adds three stratigraphy metrics

todo
 - [x] documentation
 - [x] tests

## deltametrics.strat.compute_net_to_gross

Computes a spatially-resolved net-to-gross for a deposit. This computation is based on thresholding some data to indicate what volume is “net” (usually grain size or sand fraction data).

```
golfcube = dm.sample_data.golf()
golfstrat = dm.cube.StratigraphyCube.from_DataCube(golfcube, dz=0.1)
background = (golfstrat.Z > np.min(golfcube['eta'].data, axis=0))

net_to_gross = dm.strat.compute_net_to_gross(
    golfstrat['sandfrac'],
    net_threshold=0.5,
    background=background)

fig, ax = plt.subplots(1, 2, figsize=(6, 3))
im0 = ax[0].imshow(
    net_to_gross,
    extent=golfstrat.extent)
dm.plot.append_colorbar(im0, ax=ax[0])
im1 = ax[1].imshow(
    net_to_gross,
    cmap=golfstrat.varset['net_to_gross'].cmap,
    norm=golfstrat.varset['net_to_gross'].norm,
    extent=golfstrat.extent)
dm.plot.append_colorbar(im1, ax=ax[1])
plt.tight_layout()
plt.show(block=False)
```
deltametrics-strat-compute_net_to_gross-1

## deltametrics.strat.compute_thickness_surfaces

This computation determines the deposit thickness, based on two bounding surfaces. It is a calculation of (surface - bottom_surface), with corrections to invalidate areas of no-deposition or net erosion, i.e., hightlighting only where net deposition has occurred.

```
golfcube = dm.sample_data.golf()
deposit_thickness0 = dm.strat.compute_thickness_surfaces(
    golfcube['eta'][-1, :, :],
    golfcube['eta'][0, :, :])
deposit_thickness1 = dm.strat.compute_thickness_surfaces(
    golfcube['eta'][-1, :, :],
    np.min(golfcube['eta'], axis=0))

fig, ax = plt.subplots(1, 2)
im = ax[0].imshow(deposit_thickness0)
dm.plot.append_colorbar(im, ax=ax[0])
ax[0].set_title('thickness above initial basin')
im = ax[1].imshow(deposit_thickness1)
dm.plot.append_colorbar(im, ax=ax[1])
ax[1].set_title('total deposit thickness')
plt.tight_layout()
plt.show()
```

deltametrics-strat-compute_thickness_surfaces-1

## deltametrics.strat.compute_sedimentograph
Compute the sedimentograph for an arbitrary data, but intended to be used primarily with sandfrac or other grain size data. Flexible number of bins and thresholds for computing fractions.

```
golfcube = dm.sample_data.golf()
golfstrat = dm.cube.StratigraphyCube.from_DataCube(golfcube, dz=0.1)

background = (golfstrat.Z > np.min(golfcube['eta'].data, axis=0))

(sedimentograph, radii, bins) = dm.strat.compute_sedimentograph(
    golfstrat['sandfrac'],
    num_sections=50,
    last_section_radius=2750,
    background=background,
    origin_idx=[3, 100])

fig, ax = plt.subplots()
ax.plot(
    radii,
    sedimentograph[:, 1],
    marker='o', ls='-')
ax.set_xlabel('section radius (m)')
ax.set_ylabel(f'fraction > {bins[1]}')
plt.show()
```

deltametrics-strat-compute_sedimentograph-1

## deltametrics.strat._determine_deposit_from_background

Helper for stratigraphic functions. Determine the boolean mask of the deposit, i.e., excluding the pre-deposition basin topography.

This example shows how choice of background affect the background used for stratigraphic computations.

The first background calculation simply uses the initial basin topography to determine the background voxels, but this ignores erosion and subsequent infilling.

The second background calculation considers this infilling of erosional channels by including the inflill in the deposit, and not in the background.

The third background shows the effect of using a constant value as the background value; hint: this is generally a bad idea unless your data has a background value encoded into it (like -1 or 9999).

```
golfcube = dm.sample_data.golf()
golfstrat = dm.cube.StratigraphyCube.from_DataCube(golfcube, dz=0.05)

# background determined from initial basin topography
background0 = dm.strat._determine_deposit_from_background(
    golfcube['sandfrac'],
    background=golfstrat.Z > golfcube['eta'][0].data)
# background determined from min of bed elevation timeseries
background1 = dm.strat._determine_deposit_from_background(
    golfcube['sandfrac'],
    background=(golfstrat.Z > np.min(golfcube['eta'].data, axis=0)))
# background determined from a fixed sandfrac value
background2 = dm.strat._determine_deposit_from_background(
    golfcube['sandfrac'],
    background=0)

fig, ax = plt.subplots(2, 2, figsize=(6, 4))
ax[0, 0].imshow(background0[59], cmap='Greys_r')  # just below initial basin depth
ax[0, 1].imshow(background0[60], cmap='Greys_r')  # just above initial basin depth
ax[1, 0].imshow(background1[59], cmap='Greys_r')  # just below initial basin depth
ax[1, 1].imshow(background2[59], cmap='Greys_r')  # just below initial basin depth
plt.tight_layout()
```

image

### CODE REVIEW

**Comment by amoodie** [comment]
@elbeejay any api /option suggestions? kinda threw these together today from some old codes.

**Comment by elbeejay** [comment]
probably want to add a citation to the sedimentograph docstring.

not sure how I feel about the function name `compute_thickness_surface`, but it seems to describe what it does properly, just sounds clunky to me (although maybe "thickness surface" is the right term?)

**Comment by amoodie** [comment]
will add reference :+1: 

I think I went for that because I was imagining another scenario where you may want to compute the thickness of a stratigraphic deposit from the stratigraphy itself (how, tbd). So this was a different function, in that it operated on surfaces. So maybe `compute_thickness_surfaces(...)` would be better (just adding the `s`)?

**Comment by amoodie** [comment]
wait that's what I already called it :sweat_smile:

**Comment by elbeejay** [comment]
To clarify I am fine with the name, happy to go with what you've suggested, especially since you've arrived at it twice now

**Pull request merged**
